plugins {
    id 'java'
    id 'application'
}

group = 'com.chauhan739'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Standard Java Swing/AWT app, no external dependencies needed.
}

application {
    // The main class is in the default package
    mainClass = 'FileMigratorApp'
}
